name: Deploy on NPM

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish on NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}
          package: dist

      - if: ${{ !steps.publish.outputs.type }}
        run: |
          echo "Release failed: Version not changed"
          exit 1
